- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy M"
  tasks:
    - name: print the info
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"
    - name: print the info again
      vars:
        COURSE: "Ansible"
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"
    - name: print the info again and again
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"