- name: variables from files
  hosts: web
  vars-files:
    - vars.yml
  tasks:
  - name: print the info
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"