- name: Devops course information
  hosts: local
  connection: local
  vars:
    duration: 120 #number
    course: "Devops with AWS" #string
    topics: #list
      - linux
      - git & github
      - maven
      - jenkins
      - ansible
    live: true #boolean
    tools:
      ci: jenkins
      cm: ansible
      cloud: aws
      aws:
        IAM
        S3
    tasks:
    - name: print thr course information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ course }}, with duration: {{ duration }}, topics are: {{ topics }}, and live: {{ live }}, tools are: {{ tools }}"
