- name: create user
  hosts: local
  connection: local # for localhosts
  tasks:
    - name: check user exists or not
      ansible.builtin.command: id expense # Used to run a command
      register: USER # register is used to get the output of above command and store in a USER variable like ${command} in shell scripting
    - name: print the user info
      ansible.builtin.debug:
        msg: "User info : {{USER}}"
