- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hello {{ item }}" # item is reserved keyword
    loop:
    - Ramesh
    - Suresh
    - Harish