- name: Install and remove packages using loop
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install and remove packages
    ansible.builtin.package:
      name: "{{item.name}}" # item is reserved keyword
      state: "{{item.state}}"
    loop:
    - {name: "mysql", state: "present"}
    - {name: "nginx", state: "present"}
    - {name: "tree", state: "absent"}
    - {name: "httpd", state: "absent"}