- name: create ec2 instance and r53 records
  hosts: local
  connection: local
  vars: # below values will change everytime whenever the new server creates
    vpc_subnet_id: "subnet-0f1d3a25a69ad3650"
    security_group: "sg-07374e41b5d05c16e"
    image_id: "ami-0453ec754f44f9a4a"
    instance_type: "t2.micro"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ vvpc_subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ security_group }}"
      image_id: "{{ image_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
    
